# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170330_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', 'updated']},
        ),
    ]
