# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170330_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 30, 9, 34, 8, 394591, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
